% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/functions.R
\name{summarize_by_category}
\alias{summarize_by_category}
\title{Summarize Work Orders by Category}
\usage{
summarize_by_category(df)
}
\arguments{
\item{df}{A data frame containing work order data}
}
\value{
A summary data frame with counts by category
}
\description{
This function counts the number of work orders by category.
}
